### ISSUE TITLE
4 new defect(s) introduced to dfuzzer found with Coverity Scan

### ISSUE THREAD

**Issue by evverx** [matusmarhefka/dfuzzer#27]
https://scan.coverity.com/projects/dfuzzer

On the bright side "7 defect(s), reported by Coverity Scan earlier, were marked fixed in the recent build analyzed by Coverity Scan."

**Comment by mrc0mmand** [comment]
Thanks! I'll take a look.

**Comment by evverx** [comment]
I've just sent dfuzzer to coverity and it said that "10 defect were eliminated".

**Comment by mrc0mmand** [comment]
> I've just sent dfuzzer to coverity and it said that "10 defect were eliminated".

Nice, thanks!

**Comment by evverx** [comment]
I've just opened https://github.com/matusmarhefka/dfuzzer/issues/31 because sending stuff to coverity manually is cumbersome
