### ISSUE TITLE
[feature] Full machine-readable logging

### ISSUE THREAD

**Issue by mmiszczyk** [matusmarhefka/dfuzzer#3]
It could be useful (if we're interested not just in what processes we're able to crash and how but also in what methods/signals are accessible to the current user; and if we want some kind of automated log analysis/triaging) to create parseable/machine-readable logs containing all the method calls/signals as well as their return values, thrown exceptions and whether the process crashed.

I tried implementing this feature by adding a -L command line switch, which opens a file for writing those logs. I've made a logging macro:

```c
#define FULL_LOG(fmt, ...) if(logfile) fprintf(logfile, fmt, ##__VA_ARGS__)
```

...and modified the df_fuzz_write_log() function accordingly:

```c
			switch (s->sig[0]) {
			case 'y':
				;
				guint8 tmp;
				g_variant_get(s->var, s->sig, &tmp);
				df_fail("-- '%u'\n", tmp);
				FULL_LOG("%u;", tmp);
break;
//etc.
```

I've also added a line which calls df_fuzz_write_log() after each method call if the -L switch has been passed:

```c
		if (value != NULL) {
			g_variant_unref(value);
			value = NULL;
		}
		if(logfile) df_fuzz_write_log();
		if (df_except_counter == MAX_EXCEPTIONS) {
			df_except_counter = 0;
			break;
}
```

But for some reason, it just doesn't work: the first time this modified df_fuzz_write_log() is called, the program aborts with a type check failure from Glib. I have no idea why but I guess it's related to calling the function outside of the failure condition (some differences in internal state?), not to added writing to file.

If anyone wants to take a look, [here's the branch I used to develop this functionality](https://github.com/mmiszczyk/dfuzzer/tree/logging/src).

**Comment by matusmarhefka** [comment]
I am sorry for the late reply, the failure happens because you call `df_fuzz_write_log` function after the possible `g_variant_unref` and therefore you might end up in a case where you are referencing freed memory:
```
                if (value != NULL) {
			g_variant_unref(value);
			value = NULL;
		}
		if(logfile) df_fuzz_write_log();
```
It must be called before the if statement with `g_variant_unref`:
```
		if(logfile) df_fuzz_write_log();
                if (value != NULL) {
			g_variant_unref(value);
			value = NULL;
		}
```

**Comment by matusmarhefka** [comment]
@mmiszczyk ^^

**Comment by mmiszczyk** [comment]
@matusmarhefka thanks for your help! Please see the PR #4.

**Comment by matusmarhefka** [comment]
Resolved in PR https://github.com/matusmarhefka/dfuzzer/pull/4
