### ISSUE TITLE
RFE: `dfuzzer` should probably get/set properties

### ISSUE THREAD

**Issue by evverx** [matusmarhefka/dfuzzer#61]
It should help to cover code like https://github.com/systemd/systemd/blob/main/src/shared/bus-log-control-api.c.

It's possible to get properties with `df_interface_data->properties`.

**Comment by evverx** [comment]
@mrc0mmand FWIW I think it would be great to cover code sending signals too. It can't be integrated into `dfuzzer` though because it would have to subscribe to systemd and trigger various events triggering those signals and that's out of scope here.

Regarding properties turns out it's more complicated than I thought. `dfuzzer` was supposed to call methods so all its data structures revolve around methods. Iterating over properties would be a major change (though unlike signals conceptually properties should be nicely integrated into `dfuzzer`).

**Comment by mrc0mmand** [comment]
> @mrc0mmand FWIW I think it would be great to cover code sending signals too. It can't be integrated into `dfuzzer` though because it would have to subscribe to systemd and trigger various events triggering those signals and that's out of scope here.
> 
> Regarding properties turns out it's more complicated than I thought. `dfuzzer` was supposed to call methods so all its data structures revolve around methods. Iterating over properties would be a major change (though unlike signals conceptually properties should be nicely integrated into `dfuzzer`).

I thought about properties as well, and it would certainly make sense. Signals are a bit different territory, as you said. I have a couple of patches/ideas in the pipeline to make the code cleaner/simpler, so, hopefully, after that implementing properties should be a bit easier, once we get to that.

**Comment by evverx** [comment]
> I have a couple of patches/ideas in the pipeline

Good to know. Thanks! I'm just curious, are there patches covering advanced signatures?

> once we get to that

Agreed. But generally I think the memory leak detector should be addressed first to make it possible to finally merge https://github.com/systemd/systemd/pull/22547 and start covering that DBus code with what's available.

**Comment by mrc0mmand** [comment]
> Good to know. Thanks! I'm just curious, are there patches covering advanced signatures?

Not yet, unfortunately, just dropping a lot of redundant code, making the code easier to read, untangling functions, etc. Just stuff to make introducing new code easier.
 
> Agreed. But generally I think the memory leak detector should be addressed first to make it possible to finally merge [systemd/systemd#22547](https://github.com/systemd/systemd/pull/22547) and start covering that DBus code with what's available.

Definitely. I'll rebase #53 tomorrow, so it's ready once/if we decide to merge it.

**Comment by mrc0mmand** [comment]
After reading another metric ton of GLib docs and lot of trial and error, I think I have a promising base for generating variants for arbitrary dbus signatures, but I still need to dig a bit deeper. I hope I'll get it up and working in the next couple of days.
