### ISSUE TITLE
methods receiving booleans are called 10000 times

### ISSUE THREAD

**Issue by evverx** [matusmarhefka/dfuzzer#66]
I ran into this when I pointed `dfuzzer` at `systemd-logind`. It started testing the `FlushDevices(b)` method and it looked like it got stuck.

I think it should be enough to call methods like that twice to somewhat cover them. I'm not sure how it can be implemented and how it can be combined with https://github.com/matusmarhefka/dfuzzer/pull/64 but generally it seems `dfuzzer` generates much more combinations than necessary. Without corpora it can discover only "shallow" bugs and to achieve that it should be possible to generate minimum and maximum values (because they aren't tested well usually) and something in between.

**Comment by mrc0mmand** [comment]
That would definitely make sense (and thanks for explaining why `FlushDevices(b)` takes ages, I was puzzled about that as well). The pseudo-random data generation for the methods is my next target anyway - should I add the changes on top of #64 or wait, to not make the PR unnecessarily big?

**Comment by evverx** [comment]
That PR is already big so if it's easier to add that on top I think it should be fine. It would be easier to test how those changes interact with each other.
